import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)
GPIO.setup(11,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(24,GPIO.OUT)
GPIO.setup(23,GPIO.OUT)
GPIO.output(11,True)
sleep(0.5)
GPIO.output(11,False)
GPIO.output(13,True)
sleep(0.25)
GPIO.output(13,False)
sleep(1)
GPIO.output(24,True)
sleep(0.2)
GPIO.output(24,False)
sleep(0.2)
GPIO.output(24,True)
sleep(0.2)
GPIO.output(24,False)
sleep(1)
GPIO.output(24,True)
sleep(0.2)
GPIO.output(24,False)
sleep(0.2)
GPIO.output(24,True)
sleep(0.2)
GPIO.output(24,False)

GPIO.cleanup()
